---
name: Run Rust tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'rust/**'

jobs:

  go-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Running unit tests
        run: make test
        working-directory: rust
      - name: Build app
        run: make build
        working-directory: rust
