---
name: Run Go tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'go/**'

jobs:

  go-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Running unit tests
        run: make test-coverage
        working-directory: go
      - name: Build example app
        run: make build
        working-directory: go
      - name: Lint example app
        run: make lint
        working-directory: go
